# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RatingsSDK' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RatingsSDK
  pod 'SwiftHTTP', '~> 2.0.2'
  pod 'SwifterSwift/Foundation', '~> 3.1.0'

end
